This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file /Users/johannes/Documents/Studium/6. Semester/Bachelorarbeit/Latex/ba_binder.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/johannes/Documents/Studium/6. Semester/Bachelorarbeit/Latex/ba_binder.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file /Users/johannes/Documents/Studium/6. Semester/Bachelorarbeit/Latex/ba_binder.acr....done (6 lines written, 0 warnings).
Output written in /Users/johannes/Documents/Studium/6. Semester/Bachelorarbeit/Latex/ba_binder.acr.
Transcript written in /Users/johannes/Documents/Studium/6. Semester/Bachelorarbeit/Latex/ba_binder.alg.
