kind: Service
apiVersion: v1
metadata:
  name:  frontend-svc
spec:
  selector:
    app:  frontend
  type:  NodePort
  ports:
  - name: frontend-port
    port:  4200
    targetPort: 80
    nodePort: 30500